[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[project]
name = "webgoose"
description = "Static Site Generator"
requires-python = ">=3.9"
license = {text = "GPLv3"}
version = "0.4.0-dev-R5"
dynamic = ["dependencies", "readme"]


[project.scripts]


[tool.setuptools.dynamic]
readme = {file = ["README.md"]}
dependencies = {file = ["requirements.txt"]}
