
config:
  output_dir: "."
  #other options as required


tree:
  primary:
    constr:
      builder: "webgoose.default_tree_builder"
      params:
        source_dir: "./src"

  posts:
    constr:
      builder: "my_custom.posts_tree_builder"
      add_globals: true
      params:
        source_dir: "./posts"
    mount_to: "/posts"


globals:
  #user defined global render vars
 