config:
  output_dir: "."
  force_render_update: true

site_tree:

  # Primary Source Tree
  - tree:
    constr:
      builder: "webgoose.tree.PlainTreeBuilder"
      params:
        source_dir: "./src"

  # Posts Tree
  - tree:
    mount_to: "/posts"
    constr:
      builder: "webgoose.tree.BlogTreeBuilder"
      allow_global_additions: true 
      params:
        source_dir: "./posts"


globals:
  domain: "testdomain.net"
  email: "webmaster@testdomain.net"